### ISSUE TITLE
NameError running kitchen converge on database

### ISSUE THREAD

**Issue by dhuyvetter** [learn-chef/awesome_customers_ubuntu#7]
I am following the tutorial, but on https://learn.chef.io/manage-a-web-app/ubuntu/configure-the-database/ I am stuck as `kitchen converge` throws an error:

```

   ================================================================================
   Recipe Compile Error in /tmp/kitchen/cache/cookbooks/awesome_customers_ubuntu/recipes/default.rb
   ================================================================================
   
   NameError
   ---------
   No resource, method, or local variable named `create_tables_script_path' for `Chef::Recipe "database"'
   
   Cookbook Trace:
   ---------------
     /tmp/kitchen/cache/cookbooks/awesome_customers_ubuntu/recipes/database.rb:47:in `from_file'
     /tmp/kitchen/cache/cookbooks/awesome_customers_ubuntu/recipes/default.rb:10:in `from_file'
   
   Relevant File Content:
   ----------------------
   /tmp/kitchen/cache/cookbooks/awesome_customers_ubuntu/recipes/database.rb:
   
    40:    password node['awesome_customers_ubuntu']['database']['admin_password']
    41:    database_name node['awesome_customers_ubuntu']['database']['dbname']
    42:    host node['awesome_customers_ubuntu']['database']['host']
    43:    action [:create, :grant]
    44:  end
    45:  
    46:  # Write schema seed file to filesystem.
    47>> cookbook_file create_tables_script_path do
    48:    source 'create-tables.sql'
    49:    owner 'root'
    50:    group 'root'
    51:    mode '0600'
    52:  end
    53:  
    54:  # Seed the database with a table and test data.
    55:  execute "initialize #{node['awesome_customers_ubuntu']['database']['dbname']} database" do
    56:    command "mysql -h #{node['awesome_customers_ubuntu']['database']['host']} -u #{node['awesome_customers_ubuntu']['database']['admin_username']} -p#{node['awesome_customers_ubuntu']['database']['admin_password']} -D #{node['awesome_customers_ubuntu']['database']['dbname']} < #{create_tables_script_path}"
   
   Platform:
   ---------
   x86_64-linux
```

**Comment by tpetchel** [comment]
Sorry I didn't see this. I typically look for questions in the comments section at the bottom of the tutorial pages. Please reopen if you're still seeing the issue.
